### Improting  Libraries

In [9]:
import pandas as pd
import numpy as np
import cv2
import os
import urllib.request
import requests

In [15]:
lst = ['cat', 'dog', 'elephant', 'parrot', 'cow']
n=0
arr = []
label = []
for i in lst:
    
    
    url = f"https://free-images-api.p.rapidapi.com/images/{i}"

    headers = {
        "X-RapidAPI-Key": "210c3f68bcmsh385021a1051c143p1bf373jsn1c3eb5d97ea3",
        "X-RapidAPI-Host": "free-images-api.p.rapidapi.com"
    }

    response = requests.get(url, headers=headers)
    
    df = pd.json_normalize(response.json(),record_path=['results'])
    
    folder_path = f'C:\elight-1\\{i}'
    os.makedirs(folder_path, exist_ok=True)
    
    os.chdir(f'C:\elight-1\\{i}')
    
    
    for j in df['image']:
        urllib.request.urlretrieve(j,f'C:\elight-1\\{i}\\{i}{n}.jpg')
        n = n+1
    for k in os.listdir():
        path = os.getcwd()+f'\\{k}'
        image = cv2.imread(path)
        image = cv2.resize(image,(5,4))
        arr.append(image.flatten())
        label.append(i)
data = pd.DataFrame(arr)
data['label'] = label

In [16]:
data

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,label
0,14,136,196,0,96,166,2,115,187,1,...,40,59,50,32,55,50,10,26,18,cat
1,109,140,77,120,154,83,124,158,88,121,...,68,107,146,138,148,154,61,88,118,cat
2,82,180,226,84,184,229,90,185,229,81,...,74,115,163,105,144,185,67,165,213,cat
3,108,105,104,111,109,109,117,112,113,117,...,177,182,185,66,73,76,167,171,176,cat
4,196,199,203,122,139,158,105,126,147,65,...,33,54,81,112,131,152,75,95,113,cat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,100,109,124,91,101,108,36,49,56,236,...,62,75,91,77,89,101,70,78,85,cow
96,3,3,17,230,238,238,96,120,135,230,...,148,158,168,131,147,160,133,143,153,cow
97,185,172,150,209,198,180,215,208,191,229,...,5,89,36,0,80,28,3,87,41,cow
98,203,144,95,213,156,105,215,157,108,211,...,62,115,108,35,105,103,44,90,79,cow
99,150,115,81,152,122,87,156,128,94,164,...,4,16,39,197,179,156,209,200,190,cow

In [19]:
data.to_csv('C:\elight-1\Animal.csv',index=False)